name: OCR to HTML

on:
  push:
    paths:
      - 'input_files/**'
  workflow_dispatch:

jobs:
  ocr-job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr poppler-utils
          python -m pip install --upgrade pip
          pip install pillow pytesseract pdf2image

      - name: Run OCR
        run: |
          mkdir -p output_html
          shopt -s nullglob
          for file in input_files/*; do
            base="$(basename "$file" | cut -d. -f1)"
            python scripts/ocr.py "$file" "output_html" "$base"
          done

      - name: Commit and Push results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add output_html
          git commit -m "Add OCR results [skip ci]" || echo "No changes to commit"
          git push origin main

      - name: Upload HTML results
        uses: actions/upload-artifact@v3
        with:
          name: ocr-html-results
          path: output_html/
