name: OCR to HTML

on:
  push:
    paths:
      - 'input_files/**'
  workflow_dispatch:

jobs:
  ocr-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: نصب پیش‌نیازهای OCR
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr poppler-utils default-jre libglib2.0-0

      - name: نصب پکیج‌های پایتون
        run: |
          python -m pip install --upgrade pip
          pip install pillow pytesseract pdf2image pandas openpyxl tabula-py PyMuPDF

      - name: پردازش OCR و ساخت HTML
        run: |
          mkdir -p output_texts
          mkdir -p output_html
          for file in input_files/*; do
            echo "Processing $file ..."
            filename=$(basename "$file")
            extension="${filename##*.}"
            name="${filename%.*}"

            if [[ "$extension" =~ ^(png|jpg|jpeg|bmp)$ ]]; then
              python - <<'EOF'
from PIL import Image
import pytesseract
import os

file_path = os.environ["file"]
name = os.environ["name"]

img = Image.open(file_path)
text = pytesseract.image_to_string(img, lang='eng')

# ذخیره متن خام
os.makedirs("output_texts", exist_ok=True)
with open(f"output_texts/{name}.txt", "w", encoding="utf-8") as f:
    f.write(text)

# ساخت HTML سفید
html_content = f"""<!DOCTYPE html>
<html>
<head>
<meta charset='UTF-8'>
<title>OCR Result - {name}</title>
<style>
  body {{
    background-color: white;
    color: black;
    font-family: Arial, sans-serif;
    padding: 20px;
    white-space: pre-wrap;
  }}
</style>
</head>
<body>
<h2>OCR Result</h2>
<pre>{text}</pre>
</body>
</html>
"""
os.makedirs("output_html", exist_ok=True)
with open(f"output_html/{name}.html", "w", encoding="utf-8") as f:
    f.write(html_content)
EOF
            else
              echo "Unsupported file type: $file"
            fi
          done
        env:
          file: $file
          name: $name

      - name: آپلود نتایج
        uses: actions/upload-artifact@v3
        with:
          name: ocr-results
          path: |
            output_texts/
            output_html/
