name: OCR Processing

on:
  push:
    paths:
      - 'input_files/**'    # وقتی چیزی تو input_files تغییر کنه
  workflow_dispatch:        # اجرای دستی از تب Actions

jobs:
  ocr-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: نصب پیش‌نیازهای OCR
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr poppler-utils default-jre libglib2.0-0

    - name: نصب پکیج‌های پایتون
      run: |
        python -m pip install --upgrade pip
        pip install pillow pytesseract pdf2image pandas openpyxl tabula-py PyMuPDF

    - name: پردازش فایل‌ها با OCR
      run: |
        mkdir -p output_texts
        for file in input_files/*; do
          echo "Processing $file ..."
          filename=$(basename "$file")
          extension="${filename##*.}"
          name="${filename%.*}"

          if [[ "$extension" =~ ^(png|jpg|jpeg|bmp)$ ]]; then
            python - <<EOF
from PIL import Image
import pytesseract
img = Image.open("$file")
text = pytesseract.image_to_string(img, lang='eng')
with open(f"output_texts/{name}.txt", "w", encoding="utf-8") as f:
    f.write(text)
EOF

          elif [[ "$extension" == "pdf" ]]; then
            python - <<EOF
from pdf2image import convert_from_path
import pytesseract
images = convert_from_path("$file")
text = ""
for img in images:
    text += pytesseract.image_to_string(img, lang='eng')
with open(f"output_texts/{name}.txt", "w", encoding="utf-8") as f:
    f.write(text)
EOF

          elif [[ "$extension" =~ ^(xls|xlsx)$ ]]; then
            python - <<EOF
import pandas as pd
df = pd.read_excel("$file")
df.to_csv(f"output_texts/{name}.csv", index=False)
EOF

          else
            echo "Unsupported file type: $file"
          fi
        done

    - name: آپلود نتایج به‌صورت Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ocr-results
        path: output_texts/
