name: OCR Image to HTML

on:
  push:
    paths:
      - 'input_files/**'
  workflow_dispatch:

jobs:
  ocr-html:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install OCR dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr

    - name: Install Python packages
      run: |
        python -m pip install --upgrade pip
        pip install pillow pytesseract

    - name: Process images and create HTML
      run: |
        mkdir -p output_html
        for file in input_files/*; do
          filename=$(basename "$file")
          name="${filename%.*}"

          python - <<EOF
from PIL import Image
import pytesseract

img = Image.open("$file")
text = pytesseract.image_to_string(img, lang='eng')

html_content = f"""<!DOCTYPE html>
<html>
<head>
<meta charset='UTF-8'>
<title>OCR Result - {name}</title>
<style>
  body {{
    background-color: white;
    color: black;
    font-family: Arial, sans-serif;
    padding: 20px;
    white-space: pre-wrap;
  }}
</style>
</head>
<body>
<h2>OCR Result</h2>
<pre>{text}</pre>
</body>
</html>
"""

with open(f"output_html/{name}.html", "w", encoding="utf-8") as f:
    f.write(html_content)
EOF
        done

    - name: Upload HTML result
      uses: actions/upload-artifact@v3
      with:
        name: ocr-html-results
        path: output_html/
